#!/usr/bin/env bash
# This script configures the nginx server so that /redirect_me is redirecting to another page.;
apt-get update
apt-get install nginx -y
ufw allow 22
ufw allow 80
ufw enable
echo 'Hello World!'> /var/www/html/index.html
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

service nginx restart
