#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

i=1
while [ "$1" -le 10 ]
do
   if [ "$i" -eq 4 ]; then
       echo "bad luck"
   elif [ "$i -q 8 ]; then
       echo "good luck"
   else
       echo "Best School"
   fi
   (( i++ ))
done
