#!/usr/bin/env bash
# configure SSH client to connect to server without typing a password

Host server1
    HostName 3.234.244.63
    User ubuntu
    IdentityFile ~/.ssh/school
    PasswordAuthentication no
