#!/usr/bin/env bash
# configure SSH client to connect to server without typing a password

Host server1
    HostName 3.236.229.63
    User ubuntu
    IdentityFile ~/.ssh/school
    PasswordAuthentication yes
