#!/usr/bin/env bash
# configure SSH client to connect to server without typing a password

Host server1
    HostName 46604-web-01
    User ubuntu
    IdentityFile ~/.ssh/school
    PasswordAuthentication no
